list_of_quotes = [
 'Work harder on yourself than you do on your job  ', 
 'The only way it gets better for you is when you get better. Better is not something you wish, it’s something you become  ', 
 'For things to change, you have to change  ', 
 'Don’t let your learning lead to knowledge. Let your learning lead to action  ', 
 'Success is not to be pursued, it is to be attracted by the person you become  ', 
 'Success is nothing more than a few simple disciplines practiced every day  ', 
 'When you know what you want, and you want it bad enough, you will find a way to get it  ', 
 'The few who do are the envy of the many who only watch  ', 
 'Time is more valuable than money. You can get more money, but you cannot get more time  ', 
 'Formal education will make you a living, self-education will make you a fortune  ', 
 'You are the average of the five people you spend the most time with  ', 
 'Life does not get better by chance, it gets better by change  ', 
 'All leaders are readers  ', 
 'Don’t shortchange yourself when it comes to investing in your own better future  ', 
 'Start reading, and especially read the kinds of books that will help you unleash your inner potential  ', 
 'What you become is far more important than what you get  ', 
 'I used to blame everything outside of me for my lack of progress until I found that my problem was inside  ', 
 'If you will be faithful to a few things, you will someday become the ruler over many things  ', 
 'Poor people spend their money and save what’s left, rich people save their money and spend what’s left  ', 
 'Take interest and even delight in doing the small things well  ', 
 'Living life in style also means living a life of balance  ', 
 'Few key things that make a difference, once identified, spend major time on these things  ', 
 'Life is not just the passing of time. Life is the collection of experiences and their intensity  ', 
 'You cannot change your destination overnight but you can change your direction overnight  ', 
 'Successful people do what unsuccessful people are not willing to do  ', 
 'Don’t wish it was easier, wish you were better. Don’t wish for less problems, wish for more skills. Don’t wish for less challenges, wish for more wisdom  ', 
 'Be fascinated instead of frustrated  ', 
 'Unless you change how you are, you will always have what you got  ', 
 'Either you run the day or the day runs you  ', 
 'You must take personal responsibility. You cannot change the circumstances, the seasons, or the wind, but you can change yourself. That is something you have charge of  ', 
 'Learning is the beginning of wealth. Learning is the beginning of health. Learning is the beginning of spirituality. Searching and learning is where the miracle process all begins  ', 
 'Take care of your body. It’s the only place you have to live  ', 
 'Finding is reserved for those who search  ', 
 'Motivation is what gets you started. Habit is what keeps you going  ', 
 'Happiness is not something you postpone for the future; it is something you design for the present  ', 
 'Let others lead small lives, but not you. Let others argue over small things, but not you. Let others cry over small hurts, but not you. Let others leave their future in someone else’s hands, but not you  ', 
 'Learn how to be happy with what you have while you pursue all that you want  ', 
 'Everyone must choose one of two pains: The pain of discipline or the pain of regret  ', 
 'The more you care, the stronger you can be  ', 
 'If you don’t sow, you don’t reap. You don’t even have a chance  ', 
 'To solve any problem, here are three questions to ask yourself: First, what could I do? Second, what could I read? And third, who could I ask? ”  ', 
 'A good objective of leadership is to help those who are doing poorly to do well and to help those who are doing well and to help those who are doing well to do even better  ', 
 'You must be careful not to let your current appetites steal away any chance we might have for a future feast  ', 
 'If you don’t design your own life plan, chances are you’ll fall into someone else’s plan, and guess what they have planned for you? Not much  ', 
 'The major key to your better future is you  ', 
 'If you are not willing to risk the usual you will have to settle for the ordinary  ', 
 'The worst thing one can do is not to try, to be aware of what one wants and not give in to it, to spend years in silent hurt wondering if something could have materialized  ', 
 'If you grow, everything grows for you  ', 
 'For every disciplined effort, there is a multiple reward  ', 
 'Discipline is the bridge between goals and accomplishment  ', 
 'The stronger the why, the easier the how becomes  ', 
 'We cannot move casually into a better future. We cannot casually pursue the goal we have set for ourselves. A goal that is casually pursued is not a goal, at best it is a wish, and wishes are little more than self-delusion  ', 
 'Don’t spend major time on minor things  ', 
 'Every day, stand guard at the door of your mind  ', 
 'Excuses are the nails used to build a house of failure  ', 
 'You have two choices: You can make a living, or you can design a life  ', 
]